version: '3'

services:
  db:
    image: mysql:5.6
    volumes:
      - ./scripts/fisikamu.sql:/docker-entrypoint-initdb.d/fisikamu.sql
      - ./db_data:/var/lib/mysql
    restart: always
    ports:
      - 3307:3307
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: fisikamu
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST: db
      PMA_USER: admin
      PMA_PASSWORD: admin
    ports:
      - "8080:80"
  
  apache2:
    build: apache2
    hostname: fisikamu.space
    restart: always
    volumes_from:
      - letsencryptstore
    ports:
      - "80:80"
      - "443:443"
    environment:
      LETS_ENCRYPT_EMAIL: "wilirahmatm@email.com"
      LETS_ENCRYPT_DOMAINS: "fisikamu.space"
    labels:
      io.enonic.backup.data: "/etc/letsencrypt,/var/lib/letsencrypt"
    letsencryptstore:
    image: busybox
    volumes:
      - "/etc/letsencrypt"
      - "/var/lib/letsencrypt"

  ciapp:
    build: ./ciapp
    volumes: 
      - ./ciapp:/var/www/html/
    depends_on:
       - db
    restart: always
    links:
      - db:mysql
    ports:
      - "80:80"

volumes:
    db_data:
